name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
concurrency:
  group: ${{ github.repository }}-${{ github.ref }}-${{ github.head_ref }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  tests_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          include:
            - python-version: 3.7
              TOXENV: "py37"
            - python-version: 3.8
              TOXENV: "py38"
            - python-version: 3.9
              TOXENV: "py39"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build Wheel
        run: |
            pip install --upgrade pip 
            pip install build wheel
            python -m build
        shell: bash
      - name: Install Entanglement Forging
        run: |
            cd dist && pip install -U entanglement_forging*.whl
        shell: bash
      - name: Install Test Dependencies
        run: |
            pip install .[dev]
            black --check entanglement_forging/ tests/
            python -m unittest -v
            treon docs/ --threads 5
        shell: bash
      - name: Run Tests
        run: |
            black --check entanglement_forging/ tests/
            python -m unittest -v
            treon docs/ --threads 5
        shell: bash
  tests_macOS:
    runs-on: macOS-latest
    strategy:
      matrix:
          include:
            - python-version: 3.7
              TOXENV: "py37"
            - python-version: 3.8
              TOXENV: "py38"
            - python-version: 3.9
              TOXENV: "py39"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build Wheel
        run: |
            pip install --upgrade pip 
            pip install build wheel
            python -m build
        shell: bash
      - name: Install Entanglement Forging
        run: |
            cd dist && pip install -U entanglement_forging*.whl
        shell: bash
      - name: Install Test Dependencies
        run: |
            pip install .[dev]
        shell: bash
      - name: Run Tests
        run: |
            black --check entanglement_forging/ tests/
            python -m unittest -v
            treon docs/ --threads 5
        shell: bash
